# Generated by Django 2.1.2 on 2018-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20181017_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.FloatField(default=0.6),
        ),
    ]
