# Generated by Django 2.1.2 on 2018-10-17 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0004_auto_20181017_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='lentout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='returndate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
